### PR TITLE
Fork thnkyou

### PR DESCRIPTION
**Pull request by abinaya0101**
:)

### CODE REVIEW

**Comment by ArnabXD** [comment]
Sorry, but what are you trying to do. Also, this modification will break the play command

**Comment by abinaya0101** [comment]
bolehkah saya memodifikasi file "play" dengan gambar (telegraph.png)
Pribadi?

Pada tanggal Rab, 18 Agt 2021 00:53, Arnab Paryali ***@***.***>
menulis:

**Comment by abinaya0101** [comment]
may i modify the "play" file with a private (telegraph.png) image?

Pada tanggal Rab, 18 Agt 2021 00:58, Syah Rizal ***@***.***>
menulis:

**Comment by ArnabXD** [comment]
Yes, you can do that on your fork, for this you just need to change the image URL, not the property `image` to `gambar`. 
```
image: message.audio.thumb?.file_id ?? `Your Image URL Here`, 
```

**Comment by abinaya0101** [comment]
Okay, thank you but there is one problem, in your fork repository, I can't
change image: message.audio.thumb?.file_id ?? `Your Image URL Here`, . Or
more detailed I can't write or modify

Pada tanggal Rab, 18 Agt 2021 01:05, Arnab Paryali ***@***.***>
menulis:

**Comment by ArnabXD** [comment]
This repository (ArnabXD/main) is the main repository and yours (abinaya0101/TGVCBot) is the fork.

You have the permission there in your forked repository. You already changed it once, that's how you were able to create this pull request. But you need to notice that you need to change the repo while deploying, Like clicking on Railway deploy button it won't deploy your repo, it will deploy mine. Heroku should work fine, and in case of VPS you need to clone your repo to see the changes in work

**Comment by abinaya0101** [comment]
Thank you author, good luck for the future.

Pada tanggal Rab, 18 Agt 2021 01:19, Arnab Paryali ***@***.***>
menulis:

**Pull request closed without merging**
